### ISSUE TITLE
Add Support for belongsToMany associations

### ISSUE THREAD

**Issue by wolfgangwalther** [alt3/sequelize-to-json-schemas#35]
Those are currently not listed at all.

They should probably be added here:
https://github.com/alt3/sequelize-to-json-schemas/blob/fd8da33cb7906b4316d1192f3ae67f746b2f4ca2/lib/schema-manager.js#L646

**Comment by wolfgangwalther** [comment]
And probably BelongsTo as well?

**Comment by bravo-kernel** [comment]
I am unsure which are/could be supported but you are correct, that is the place where the current associations are being handled. I took the inspiration from another lib which also only handles `HasOne` and `hasMany`.

Open to all suggestions.

**Comment by bravo-kernel** [comment]
@wolfgangwalther Not to scare you off but please be aware (beforehand) that adding them could require quite some work as other parts will probably have to be updated as well. However, I could assist you there and pick up some remaining tasks like generating the examples. 

I basically did not get to implementing them because my app has not reached this point yet.
